import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const ibmPlex = IBM_Plex_Mono({
  variable: "--font-ibm-plex",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

const chicagoKare = localFont({
  variable: "--font-chicago-kare",
  src: [
    {
      path: "../fonts/ChicagoKare-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/ChicagoKare-Regular.woff",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Gabriel Pereira - Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ibmPlex.variable} ${chicagoKare.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
